### ISSUE TITLE
Brain RE1 - No VTX config on MultiPort

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1171]
- Seen in version (release version or githash): 5f25d7d4
- On flight controller (if applicable): Brain RE1

Issue details:
  There is no VTX config option on the MultiPort in GCS for the Brain RE1.

**Comment by mluessi** [comment]
This is because TBS SmartAudio uses weird signal levels that don't work with the bidirectional pass-through the FPGA on RE1. Basically, the idle signal level is low (like inverted serial) but the actual signal is non-inverted serial. The FPGA can either handle inverted serial or non-inverted serial, but not this odd mix that TBS decided to use. You can just use the serial port for the VTX config and probably also the audio port in the future.
