### ISSUE TITLE
Feature: Add forum user id to upload, add button to download all tune data as a CSV,

### ISSUE THREAD

**Issue by ragd011** [d-ronin/dRonin#1204]
- Seen in version (release version or githash): N/A
- On flight controller (if applicable): N/A

Issue details:  It would be nice to reach out to someone with an identical setup and ask how it flies and what settings they landed on in the end.  Also, if we can download the data via csv, you can filter the results by, board, size, cell count etc.  and be able to make some direct comparisons very quickly.

**Comment by mlyle** [comment]
@ragd011 We've discussed to have the ability to claim tunes.

There is an API to export tunes en masse-- http://dronin-autotown.appspot.com/api/recentTunes and http://dronin-autotown.appspot.com/api/tune?tune=ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoJeK8ggM   (example url).

We've talked about having the ability to "claim tunes" so that they could be further annotated later, etc.  But so far we've not done any user management for it.
