### ISSUE TITLE
Vehilce Setup Wizard resets items set by Radio Setup Wizard

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1288]
- Seen in version (release version or githash): http://jar.lyle.org:8080/job/dronin/577
- On flight controller (if applicable): AQ32

Issue details:

When you first run the Radio Setup Wizard, and then the Vehicle Setup Wizard, at RC Input the Throttle, Roll, Pitch, Yaw and FlightMode settings, at Flight Mode Switch Settings and Arming Settings are all reset.

I did it in that order, and skipped the Radio Wizard option at the end of the Vehicle Setup Wizard (did think to myself, I did already setup that). Was expecting to be able to fly. No joy, after connecting back to the GCS, I noticed those settings changed.

Could be that I was doing it in the wrong order.
Might confuse new users also.

**Comment by tracernz** [comment]
Intentional, because you select a new receiver type in the wizard. The radio wizard is supposed to run AFTER the setup wizard, hence it offers to do that. https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp#L364 It should really clear the other channels if it's going to do that though...

**Comment by yamahabest** [comment]
Agree, should do all channels then, yes.
