### ISSUE TITLE
dRonin logo doesn't play nicely with a black Windows task bar

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1349]
- Seen in version (release version or githash): -
- On flight controller (if applicable): -

Issue details:
The letters are "invisible".
I believe @mlyle already has some updated icons, which include some white lining around the logo.

**Comment by tracernz** [comment]
Which icon are we using, because branding/gcs.ico looks like it should be fine and I vaguely remember seeing it on Windows. Must be grabbing the transparent PNGs from somewhere for the Windows 7+ taskbar icon?

**Comment by jhitesma** [comment]
You mean a black title bar?  Because a black (or at least dark grey....but doesn't look like it would matter) taskbar looks ok to me:

![image](https://cloud.githubusercontent.com/assets/2054286/18622005/3baff35e-7ddf-11e6-9c74-b447cfd223e1.png)

Black title bar though does look pretty crummy:
![image](https://cloud.githubusercontent.com/assets/2054286/18622017/65818904-7ddf-11e6-9578-9335049e4961.png)

**Comment by yamahabest** [comment]
Ehm.. Yes, that also.
However, I should have taken a screenshot of it happening, as I can't seem to reproduce it anymore on the task bar. It looked the same as your screenshot of the titlebar. Letters dissapeared against the black background, only the orange triangles visible.

**Comment by yamahabest** [comment]
Reproduced: https://snag.gy/OaIkvY.jpg

**Comment by mlyle** [comment]
Any idea how you reproduced it?  Any chance that machine just has an outdated icon that isn't getting replaced by the install?
