### ISSUE TITLE
DIY FrSky F802 Rx Sbus not working properly - frame pulse issue

### ISSUE THREAD

**Issue by macfly1202** [d-ronin/dRonin#1451]
* Seen in version : last version Naze from dRonin install package
* On flight controller : Naze
* Rx used : micro F802 from banggood http://www.banggood.com/Eachine-X73-Micro-FPV-Racing-Quadcopter-Spare-Parts-DIY-Frsky-802-8CH-SBUS-Receiver-p-1093309.html?rmmds=search
* Rx firmware used : DIY FrsKy firmware Rx F802 (from Midelic : https://www.rcgroups.com/forums/showthread.php?t=2124647&highlight=RSSI+channel+9%2B) 

This RX output in SBUS 9ms Frame pulse: 8ch + RSSI on ch9.
It seems this is not correctly recognised because of specific frame rate. 
I want to add, I used the same RX on this Naze (x73 brushed from banggood) before upgrading firmware for Telemetry and RSSI. 
2 videos to show symptom :https://youtu.be/4SP-Iud-ws8 
and 
https://youtu.be/-FXJUHMw-as

This config working perfectly on cleanflight and betaflight usart2 rx and SBUS. 

Thanks !

**Comment by mlyle** [comment]
It looks like it's working correctly, but that you're not following the instruction/warning to set the RSSI channel before going into the input wizard.  Thus the RSSI ends up getting set as your throttle channel since it's "moving" immediately at the beginning of setup.

http://i.imgur.com/yxNhgmZ.png

On the next video, your ranges are set wrong but it looks like the RX subsystem is working fine..

Perhaps next time consider asking the forum instead of filing a bug.
