### ISSUE TITLE
Autotune forum share button placement maybe not ideal

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#149]
![](https://cloud.githubusercontent.com/assets/9995998/11548405/bee4d856-99c0-11e5-85f9-94553ae6a6ea.png)

The lower right button is "close".

Usually the lower right button is what you want to do by default, "next" or whatever.  So this is counterintuitive.

**Comment by dustin** [comment]
Yeah, the buttons aren't obvious.  It's also not obvious that it's safe to
close when you're done.

I want "just do both things and close" as the bottom right button.

**Comment by mlyle** [comment]
Someone on IRC (I think @dustin) suggested a checkbox that says share, that defaults checked... that does so when you click close.

**Comment by dustin** [comment]
I didn't suggest it, but I agree with it.  I think we're missing a lot of
shares there just because it's not even a thing that occurs to people is
possible.  And/or it's something they think they have to get perfect first.

This is also an area where a UUID for the installation would be useful, as
we could flag that and have messaging back to the install/board that says,
"Our mechanical turk has done further processing on your tune data and
noticed an opportunity for improvement..."

**Comment by tracernz** [comment]
Usage stats should tell us if we're missing any..

**Comment by dustin** [comment]
People don't seem to understand the share button.  I've seen some duplicates shares as well as untuned shares.  I get the feeling some people think it opts them in for sharing.

**Comment by DTFUHF** [comment]
It'd be nice to have a link to the database as well!

**Comment by dustin** [comment]
Yes, it (usually) returns the URL to the tune it just wrote. If we make
this not require a specific action from the user, that could get more
complicated.
