### ISSUE TITLE
Large amounts of jitter on Sparky2 OneShot outputs

### ISSUE THREAD

**Issue by droidicus** [d-ronin/dRonin#323]
Attached are a few screenshots from an oscope, showing large variations in pulse-to-pulse spacing. The frequency of the oneshot pulses themselves is consistent, but the offset of some of the pulses seem to be variable in time.

![scope_8](https://cloud.githubusercontent.com/assets/6981482/11920438/d50449b6-a73d-11e5-8f25-e300d0e37424.png)
![scope_9](https://cloud.githubusercontent.com/assets/6981482/11920442/d505f66c-a73d-11e5-80f1-e1b9da46abb5.png)
![scope_10](https://cloud.githubusercontent.com/assets/6981482/11920441/d504e646-a73d-11e5-8757-25dd7543cb0f.png)
![scope_11](https://cloud.githubusercontent.com/assets/6981482/11920439/d5046b3a-a73d-11e5-8b87-8c28d1c0e3e8.png)
![scope_12](https://cloud.githubusercontent.com/assets/6981482/11920440/d504ca08-a73d-11e5-8b58-d8418a77b061.png)

**Comment by droidicus** [comment]
These screenshots were taken on a Sparky2 running PR2 firmware, quad was idle.

**Comment by mlyle** [comment]
This doesn't look too too bad-- individual delayed pulses.

**Comment by mlyle** [comment]
In Renatus at least for now.

**Comment by droidicus** [comment]
This is also causing pulses to merge together into a single, larger, pulse as well. This pulse is longer than the maximum oneshot pulse time by quite a bit (~404 us).

![scope_13](https://cloud.githubusercontent.com/assets/6981482/11920881/3db15c7e-a748-11e5-881a-5a93031210b2.png)

**Comment by droidicus** [comment]
It appears that all of the channels are showing the same behavior in a synchronous manor. Here is channel 1 and 4:
![scope_14](https://cloud.githubusercontent.com/assets/6981482/11920905/f98364a6-a748-11e5-837b-cb91d42d35ec.png)

**Comment by AlessioMorale** [comment]
This is actually the same issue i have observed in our (LP) firmware. I've tracked down the problem (using several performance counters to measure individual chain delays) being an inconsistent latency from gyro interrupt to the actuator module update (although I've added a pulse skip logic to prevent the "pulse merge" issue, needed by Sync-PWM implementation). I guess (i'm working on that direction) that the best and easier solution is some kind of "fast lane" approach from sensor input -> stabilization inner loop -> actuator.

**Comment by mlyle** [comment]
It certainly could make sense to more tightly integrate sensors and stabilization -- like we have on the F1 targets.

We used to have a pretty bad issue where sparky2 radio reinit was causing jitter, but @peabody124 has mostly fixed that.  The causes are probably slightly different due to drift between Tau/dR and LP, but probably this either relates to us doing something expensive with interrupts masked or a high priority task.  In dRonin right now, ManualControl, Stabilization, Actuator, and individual PiOS sensor tasks   are HIGHEST priority.  But sensors and attitude are HIGH.  So there's a lot of opportunities for something to run too long and create jitter.

**Comment by droidicus** [comment]
looks like this is the OP/LP commit that implements the pulse skip for them, not sure if this is useful for us with the diverged codebase and all: https://bitbucket.org/librepilot/librepilot/commits/752f3447d2489cf6c0c4508bd72a970b0805257f

**Comment by sim-** [comment]
Note that it sure would be nice if there were some guard time for minimum low time or else problems like this may cause pulses to "crash" together and cause signalling issues, as seen on other platforms: http://0x.ca/sim/tmp/cleanflight_oneshot_mind_the_gap.png . Even if not an electrical issue, many Atmel ESCs can't measure less than a microsecond or two, because the edge to be looked for next must be flipped in the receiving interrupt (no hardware PWM RX).

**Comment by droidicus** [comment]
@sim, agree. The OP/LP has a 50 us minimum low period in their pulse-skip algorithm, that seems like a good value. Less then this wouldn't really be helpful anyway, even if the ESC was able to reliably read it.

**Comment by tracernz** [comment]
Yep, we need something like that. 50 us or half of the minimum pulse-width would do.

**Comment by droidicus** [comment]
@tracernz I like the idea of half the minimum pulse width even more, that way it will scale well if we go to oneshot42 or whatever else.

**Comment by tracernz** [comment]
It would be a little limiting for Oneshot1000, `1 / (2000e-6 + 500e-6) = 400 Hz` would be okay though I guess.

**Comment by mlyle** [comment]
Opened #337 for the more severe issue (pulse merge).  Deferring this one out of Renatus.

**Comment by droidicus** [comment]
Fixed in #342

**Comment by mlyle** [comment]
#342 fixed #337 (pulse merge) ; a need for a jitter study and RTOS work remains, particularly during logging

**Comment by mlyle** [comment]
I scoped sparky2 .  occasional 150-200us jitters during logging.  I don't care that much. :P
