### ISSUE TITLE
Engines may arm at startup with invalid RC input settings

### ISSUE THREAD

**Issue by hernick-qc** [d-ronin/dRonin#362]
As shown by this configuration file with invalid RC input settings https://gist.github.com/hernick-qc/f8da724a66874ba9d7b1

Some invalid RC input configurations result in uncommanded arming at startup. If autotune is also configured, autotuning may also begin automatically as soon as the battery is plugged in.

**Comment by mlyle** [comment]
Basically the issue is that input is effectively randomized.  It's easy to get a spurious corner arming, etc.

The fix is that flight should enforce a minimum range on inputs.  We can't unconditionally protect the user, but it should be possible to make this a lot less likely.

@hernick-qc, thank you for finding this and the bug report.
