### ISSUE TITLE
Vibration test sucks.

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#610]
- The way the configuration works in GCS is extremely fidgety; requires restart of GCS to pick up a new number of spectrogram bins / easy to provoke to crash.
- Only can seem to run it with 64 or fewer bins.  With more bins, data never shows up.
- One UAVO instance per output point.
- With that, what's one left with?  64 bins is not much spectral data. 
- Why even do the FFT flight side to begin with?  There's no buffering / accumulation of the spectral energy after FFT.  There's no magical downsampling.  It boxcar's accelerometer data, and then when it has 64 points, dumps 64 points into the FFT and gets bins out.  Might as well just hand the raw accumulated accel data to GCS to do less retarded things with it.

I nominate for removal.

**Comment by jpbarraca** [comment]
From a user perspective:
- GCS support is bad due to the required restart. However that can be easily fixed.
- It's fidgety but works and is rather useful.
- With a Sparky 2.0 I'm also experiencing loss of data with more than 64 bins.

EDIT: unrelated ~~Do we have the bandwidth in the telemetry channel to report vibration data more often (1-5ms)?~~

**Comment by jpbarraca** [comment]
@mlyle Please check PR #822 as an initial attempt at this issue.
