### ISSUE TITLE
Cannot flash using windows 10

### ISSUE THREAD

**Issue by reubenfirmin** [d-ronin/dRonin#925]
Filing this on behalf of a third party. The board is a CC3D.

Issue 1) They couldn't find bu_coptercontrol.tlfw in their install.

Issue 2) The "flash" button doesn't enable.

See attached with screenshots.

[Windows%2B_install_%2Brunning%2Bin%2Bwindows%2B10%2B (1).pdf](https://github.com/d-ronin/dRonin/files/217137/Windows.2B_install_.2Brunning.2Bin.2Bwindows.2B10.2B.1.pdf)

**Comment by mlyle** [comment]
The target name is now 'cc3d' to eliminate confusion.  bu_cc3d is in the list in the screenshot.  It looks like they got bu_coptercontrol.tlfw from the previous release?

'flash' is not enabled because they are connected to firmware (note the telemetry activity lights, alarms, artificial horizon at the lower right), and not a bootloader.  The 'enter bootloader' will send an IAP command to enter the bootloader.  But really, all they should on 04/10 is plug in the board, and it will figure out whether it needs a bootloader upgrade or whatever.

https://dronin.readme.io/docs/getting-started
